# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0002_index_ip_and_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='object_pk',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID'),
        ),
    ]
