# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0002_index_ip_and_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Hit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='Hit',
            name='hitcount',
        ),
        migrations.DeleteModel(
            name='Hit',
        ),
        migrations.RemoveField(
            model_name='HitCount',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='HitCount',
        ),
    ]
