# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-11 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0004_auto_20180427_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='ip',
            field=models.CharField(db_index=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='hit',
            name='session',
            field=models.CharField(db_index=True, editable=False, max_length=40),
        ),
    ]
